### ISSUE TITLE
caddy2如何设置ip限制

### ISSUE THREAD

**Issue by vitaminx** [phpple/caddy2-cn-doc#1]
caddy2如何设置ip限制，做如下设置报错
ipfilter / {
    rule allow
    ip ***.***.***.**
}

**Comment by imlison** [comment]
ipfilter插件是caddy1的，如果想要在caddy2上使用，需要重新编译caddy。另外，貌似ipfilter很久没更新了，我试了下在caddy2上编译不成功。可以参考它的[源码](https://github.com/pyed/ipfilter) ，自己重写一个

**Comment by vitaminx** [comment]
> ipfilter插件是caddy1的，如果想要在caddy2上使用，需要重新编译caddy。另外，貌似ipfilter很久没更新了，我试了下在caddy2上编译不成功。可以参考它的[源码](https://github.com/pyed/ipfilter) ，自己重写一个

谢谢回复！
已经解决了
在caddy2里面直接有相关设置参数！
