### ISSUE TITLE
安装脚本有更新

### ISSUE THREAD

**Issue by crazypeace** [phpple/caddy2-cn-doc#2]
https://caddyserver.com/docs/install#debian-ubuntu-raspbian

**Comment by comdeng** [comment]
能具体指出哪部分内容有更新，或者提交一个pr吗？

**Comment by crazypeace** [comment]
我不知道为什么现在官方链接打不开了。
官方的安装脚本已经更新为：
```
sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
sudo apt update
sudo apt install caddy
```

**Comment by comdeng** [comment]
> 我不知道为什么现在官方链接打不开了。 官方的安装脚本已经更新为：
> 
> ```
> sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
> curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
> curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
> sudo apt update
> sudo apt install caddy
> ```

已经修改好，非常感谢您的反馈。

**Comment by crazypeace** [comment]
> > 我不知道为什么现在官方链接打不开了。 官方的安装脚本已经更新为：
> > ```
> > sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
> > curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
> > curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
> > sudo apt update
> > sudo apt install caddy
> > ```
> 
> 已经修改好，非常感谢您的反馈。

谢谢你的付出！

虽然我个人觉得官方的文档、语法都还在持续变化，做一个中文本地化工作却不参与在官方组织里面 是一件很难的事情。甚至我觉得不是一个很好的时机。
但是非常佩服你！

也许你应该用某种网页监控机器人帮你关注官方文档的变化？

**Comment by comdeng** [comment]
> 

非常感谢您的建议。
这个项目纯粹作为个人兴趣在更新，还好有你们的及时反馈。

只是非常喜欢caddy非常精巧的工作模式，想让更多人也了解到它而已。
