### ISSUE TITLE
虽然我知道看的人不多，但还是想问下~~

### ISSUE THREAD

**Issue by zurica2013** [phpple/caddy2-cn-doc#3]
大部分内容是谷歌机翻吗？

比如，
原文：All matchers that are not path or wildcard matchers must be named matchers
翻译：所有不是路径或通配符匹配器的匹配器都必须命名为匹配器

而且还没有翻完 ...

**Comment by comdeng** [comment]
机器翻译+人工review，全部人工工作量太大了。

有空的时候逐步翻译，也欢迎大家一起pr，这样完成效率会更高一些。

**Comment by comdeng** [comment]
已经基本翻译完了！
