### ISSUE TITLE
reverse_proxy 官方有更新

### ISSUE THREAD

**Issue by crazypeace** [phpple/caddy2-cn-doc#4]
https://caddy2.dengxiaolong.com/docs/caddyfile/directives/reverse_proxy

```
reverse_proxy https://example.com {
	header_up Host {upstream_hostport}
	header_up X-Forwarded-Host {host}
}
```

现在官方已经不用 `header_up X-Forwarded-Host {host}` 了

**Comment by crazypeace** [comment]
官方source:
https://caddyserver.com/docs/caddyfile/directives/reverse_proxy

**Comment by comdeng** [comment]
已修复，感谢反馈。
