### ISSUE TITLE
file_server 代码不应该翻译

### ISSUE THREAD

**Issue by Ymriri** [phpple/caddy2-cn-doc#6]
https://caddy2.dengxiaolong.com/docs/caddyfile/directives/file_server

```
file_server {
	隐藏.git
}
```
应该直接就是hide

**Comment by comdeng** [comment]
> https://caddy2.dengxiaolong.com/docs/caddyfile/directives/file_server
> 
> ```
> file_server {
> 	隐藏.git
> }
> ```
> 
> 应该直接就是hide

已修复，感谢反馈
