### ISSUE TITLE
flush_interval翻译内容不完整

### ISSUE THREAD

**Issue by tiansin** [phpple/caddy2-cn-doc#7]
我反向代理sse,按照网上说的要添加**flush_interval -1**,最后发现服务器cpu越跑越高,研究了半天发现原因是caddy在客户端断开sse后,并没有主动断开后端反向代理的连接,导致后端的sse连接越来越多...最后看英文文档才发现多了几句话. 

flush_interval 是一个[持续时间值](https://caddyserver.com/docs/conventions#durations)，用于调整 Caddy 将响应缓冲区刷新到客户端的频率。默认情况下，不进行定期刷新。负值（通常为 -1）表示“低延迟模式”，该模式完全禁用响应缓冲并在每次写入客户端后立即刷新，**并且即使客户端提前断开连接也不会取消对后端的请求**。如果响应满足以下条件之一，则忽略此选项，并且响应会立即刷新到客户端

不知道是不是加粗的那句话的原因,最后我把**flush_interval**设置成0就正常了

**Comment by comdeng** [comment]
对比了一下官方文档，的确应该是在后续版本里边调整了这块的文档。已经把stream这块的内容都统一调整了一下。感谢反馈。

具体参见：https://github.com/phpple/caddy2-cn-doc/commit/1be338ec154efd8eb75689825378c54a852f1e89
